[book]
title = "微雪博客"
authors = ["TinySnow"]
language = "zh-CN"
description = "南国微雪的博客"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "Ayu"
# google-analytics = "GTM-5VTTZ9C"
# no-section-label = true
additional-css = ["theme/customized/style.css"]
additional-js = ["assets/custom.js", "assets/bigPicture.js"]
git-repository-url = "https://github.com/TinySnow/TinySnow.github.io"
git-repository-icon = "fab-github"
input-404 = "404.md"
mathjax-support = true

[output.html.print]
enable = true
page-break = true

[output.html.fold]
enable = true
level = 0

# [preprocessor.toc]
# command = "mdbook-toc"
# renderer = ["html"]

# [build]
# use-default-preprocessors = false

[output.html.search]
enable = false